travis:
  secure:
    BINSTAR_TOKEN: w2oqQRNkM2iYMcFMSgXz+XGUNetvjA2kADqInscGOyz7q6ERlriJ+GwVSwWPBImp4Bm98hKESR2wA1kyxTIzaDRp3VE9iwOJqHPK8F4c2mWle/2Px4RZgeNO8nSFf6/PA9AqoZ5Q4O23ufFd6JJxJ4mirYOwJoYPCiOTnMoh6xyCpu+VwYdbg3L1uGdqVgXEO81YGBywLmj0ZFmr4y7EXJW3CGEyoHfHT1vPD9goFLPOM5ehBPypjvFzUNYzkRQissb23DbqQJDADQyEIUhPwTKgPTYquryOSSYF3Kng8om0KdRBsvg/RwlYIitrUPHW0JXvnwZUfpLVN0fTHkf3t0eBGcsMX/3xplK+AGJUQ0bRH8FXI34PpiAwujCxsFE8Eot7X1Zd+dcq0lw5srY5hQFvaDOxU0iRVciMgP0+Mf4rZBVZ79fSEzPNbh2MrYrS5p3x34CXwizCm9mXgKyNw+dHbfiKks9u4kutyQBO5Fr1cR6rccCw0Ybd5s5DF4X0Vl+Snb7TTdRG6pXTlILnOw5Btl7lqiwhEjxi8K8WSfBF+PS21ryimnGtJzVBoZUBglXRYKi2sDdgwR01qaW7nwRcnPYD76fIE6jIE6higRjLQrLwodLX/KhXnenx0vmbU43xW18ScHcZngbw+x7H/ph8NPC9eSTNN9SRKDgabtY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
